### PR TITLE
[scenario_logger] Fix toJson() declarations

### PR DESCRIPTION
**Pull request by fred-apex-ai**
Fix the declarations of free functions that were broken during porting in https://github.com/tier4/scenario_runner.iv.universe/pull/7

The issue only came up as a consumer actually used this package in https://github.com/tier4/scenario_runner.iv.universe/pull/28
```
Starting >>> scenario_runner
--- stderr: scenario_runner                                       
/usr/bin/ld: /home/frederik.beaujean/AutowareArchitectureProposal/install/scenario_logger/lib/libscenario_logger.so: undefined reference to `scenario_logger::toJson[abi:cxx11](scenario_logger_msgs::msg::LoggedData_<std::allocator<void> > const&)'
```

These kinds of linker errors would have come up immediately if there had been unit tests to create an executable

### CODE REVIEW

File: logger/scenario_logger/include/scenario_logger/logger.h [hunk 1]
```diff
@@ -114,8 +114,8 @@ const rclcpp::Time& begin();
 std::string toIso6801(const rclcpp::Time& stamp);
 
 boost::property_tree::ptree toJson(const scenario_logger_msgs::msg::MetaData& data);
-boost::property_tree::ptree toJson(const scenario_logger_msgs::msg::LoggedData& data);
-boost::optional<boost::property_tree::ptree> toJson(const scenario_logger_msgs::msg::Log& data,
+boost::optional<boost::property_tree::ptree> toJson(const scenario_logger_msgs::msg::Log& data);
```
Comment (fred-apex-ai) [inline logger/scenario_logger/include/scenario_logger/logger.h:117]: Easy to get lost here because the naming is so confusing, we have `Log& data`, `LoggedData& data`, `Logger`, `Logger log` etc.

**Review by esteve — APPROVED** [review]
